<?php

namespace SL\PlatformBundle\Repository;

/**
 * AdvertLanguageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertLanguageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getQueryBuilder() {
        return $this->createQueryBuilder('l')
                ->leftJoin('l.language', 'al')
                ->addSelect('al')
        ;
    }
}
