<?php

namespace SL\PlatformBundle\Repository;

/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */

use SL\PlatformBundle\Entity\Advert;

class AdvertRepository extends \Doctrine\ORM\EntityRepository
{
}
