sl_platform_home:
    path:      /{page}
    defaults: 
        _controller: SLPlatformBundle:Advert:index
        page:        1
    requirements:
        page: \d*
    
sl_platform_view:
    path:      /advert/{id}
    defaults: { _controller: SLPlatformBundle:Advert:view }
    requirements:
        id: \d+

sl_platform_add:
    path:      /add
    defaults:
        _controller: SLPlatformBundle:Advert:add

sl_platform_edit:
    path:      /edit/{id}
    defaults:
        _controller: SLPlatformBundle:Advert:edit
    requirements:
        id: \d+

sl_platform_delete:
    path:      /delete/{id}
    defaults:
        _controller: SLPlatformBundle:Advert:delete
    requirements:
        id: \d+
        
sl_platform_test:
    path:      /test
    defaults:
        _controller: SLPlatformBundle:Advert:test